apiVersion: apps/v1
kind: Deployment
metadata:
  name: gesuch-app
  labels:
    app: gesuch-app
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gesuch-app
  template:
    metadata:
      labels:
        app: gesuch-app
    spec:
      restartPolicy: Always
      containers:
        - name: gesuch-app
          imagePullPolicy: Always
          image: stip/gesuch-app
          env:
            - name: APP_NAME
              value: gesuch-app
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /_health
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /_health
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      imagePullSecrets:
        - name: dvbern-public-registry
