/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 */
export type Ausbildungssituation = 'VORSCHULPFLICHTIG' | 'SCHULPFLICHTIG' | 'IN_AUSBILDUNG' | 'KEINE';

export const Ausbildungssituation = {
    VORSCHULPFLICHTIG: 'VORSCHULPFLICHTIG' as Ausbildungssituation,
    SCHULPFLICHTIG: 'SCHULPFLICHTIG' as Ausbildungssituation,
    IN_AUSBILDUNG: 'IN_AUSBILDUNG' as Ausbildungssituation,
    KEINE: 'KEINE' as Ausbildungssituation
};

