export type Bildungsart =
  | 'BERUFSVORBEREITENDES_SCHULJAHR_VORLEHRE'
  | 'GYMNASIALE_MATURITAETSSCHULEN'
  | 'SCHULEN_FUER_ALLGEMEINBILDUNG'
  | 'VOLLZEITBERUFSSCHULEN'
  | 'LEHREN_ANLEHREN'
  | 'BERUFSMATURITAET_NACH_LEHRE'
  | 'HOEHERE_BERUFSBILDUNG'
  | 'FACHHOCHSCHULEN'
  | 'UNIVERSITAETEN_ETH';

export const Bildungsart = {
  BERUFSVORBEREITENDES_SCHULJAHR_VORLEHRE:
    'BERUFSVORBEREITENDES_SCHULJAHR_VORLEHRE' as Bildungsart,
  GYMNASIALE_MATURITAETSSCHULEN: 'GYMNASIALE_MATURITAETSSCHULEN' as Bildungsart,
  SCHULEN_FUER_ALLGEMEINBILDUNG: 'SCHULEN_FUER_ALLGEMEINBILDUNG' as Bildungsart,
  VOLLZEITBERUFSSCHULEN: 'VOLLZEITBERUFSSCHULEN' as Bildungsart,
  LEHREN_ANLEHREN: 'LEHREN_ANLEHREN' as Bildungsart,
  BERUFSMATURITAET_NACH_LEHRE: 'BERUFSMATURITAET_NACH_LEHRE' as Bildungsart,
  HOEHERE_BERUFSBILDUNG: 'HOEHERE_BERUFSBILDUNG' as Bildungsart,
  FACHHOCHSCHULEN: 'FACHHOCHSCHULEN' as Bildungsart,
  UNIVERSITAETEN_ETH: 'UNIVERSITAETEN_ETH' as Bildungsart,
};
