/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type DokumentTyp = 'PERSON_IN_AUSBILDUNG_DOK' | 'AUSBILDUNG_DOK' | 'ELTERN_DOK' | 'PARTNER_DOK';

export const DokumentTyp = {
    PERSON_IN_AUSBILDUNG_DOK: 'PERSON_IN_AUSBILDUNG_DOK' as DokumentTyp,
    AUSBILDUNG_DOK: 'AUSBILDUNG_DOK' as DokumentTyp,
    ELTERN_DOK: 'ELTERN_DOK' as DokumentTyp,
    PARTNER_DOK: 'PARTNER_DOK' as DokumentTyp
};

