/**
 * STIP Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BackendLocalDateTS } from '../types';
import { Anrede } from './anrede';
import { AdresseDTO } from './adresseDTO';

export interface ElternDTO {
  id: string;
  sozialversicherungsnummer: string;
  name: string;
  vorname: string;
  geschlecht: Anrede;
  telefonnummer: string;
  geburtsdatum: BackendLocalDateTS;
  identischerZivilrechtlicherWohnsitz: boolean;
  sozialhilfebeitraegeAusbezahlt: boolean;
  ausweisbFluechtling: boolean;
  ergaenzungsleistungAusbezahlt: boolean;
  adresse: AdresseDTO;
}
