/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { ElternTyp } from './elternTyp';

/**
 * 
 */
export interface ElternUpdate { 
    vorname: string;
    adresse: Adresse;
    identischerZivilrechtlicherWohnsitz: boolean;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzOrt?: string;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzPLZ?: string;
    telefonnummer: string;
    sozialversicherungsnummer: string;
    /**
     * dd.MM.YYYY
     */
    geburtsdatum: string;
    sozialhilfebeitraegeAusbezahlt: boolean;
    ausweisbFluechtling: boolean;
    ergaenzungsleistungAusbezahlt: boolean;
    id?: string;
    elternTyp: ElternTyp;
    nachname: string;
}



