/**
 * STIP Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchDTOFall } from './gesuchDTOFall';
import { PersonInAusbildungContainerDTO } from './personInAusbildungContainerDTO';
import { GesuchDTOGesuchsperiode } from './gesuchDTOGesuchsperiode';
import { Gesuchstatus } from './gesuchstatus';

export interface GesuchDTO {
  id: string;
  fall: GesuchDTOFall;
  gesuchsperiode: GesuchDTOGesuchsperiode;
  personInAusbildungContainer?: PersonInAusbildungContainerDTO;
  gesuchStatus: Gesuchstatus;
  gesuchNummer: number;
}
