/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GesuchFormular } from './gesuchFormular';
import { Gesuchstatus } from './gesuchstatus';
import { Fall } from './fall';
import { Gesuchsperiode } from './gesuchsperiode';

/**
 * 
 */
export interface Gesuch { 
    fall: Fall;
    gesuchsperiode: Gesuchsperiode;
    gesuchStatus: Gesuchstatus;
    /**
     * 
     */
    gesuchNummer: number;
    id: string;
    gesuch_formular_freigabe_copy?: GesuchFormular;
    gesuch_formular_to_work_with?: GesuchFormular;
}



