/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Eltern } from './eltern';
import { PersonInAusbildung } from './personInAusbildung';
import { Ausbildung } from './ausbildung';
import { Geschwister } from './geschwister';
import { Kind } from './kind';
import { Familiensituation } from './familiensituation';
import { Auszahlung } from './auszahlung';
import { Partner } from './partner';
import { LebenslaufItem } from './lebenslaufItem';

export interface GesuchFormular {
  id: string;
  ausbildung?: Ausbildung;
  auzahlung?: Auszahlung;
  familiensituation?: Familiensituation;
  /**
   *
   */
  elterns?: Array<Eltern>;
  /**
   *
   */
  kinds?: Array<Kind>;
  /**
   *
   */
  lebenslaufItems?: Array<LebenslaufItem>;
  partner?: Partner;
  personInAusbildung?: PersonInAusbildung;
  /**
   *
   */
  geschwisters?: Array<Geschwister>;
}
