/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 */
export type Kontoinhaberin =
  | 'GESUCHSTELLER'
  | 'VATER'
  | 'MUTTER'
  | 'SOZIALDIENST_INSTITUTION'
  | 'ANDERE';

export const Kontoinhaberin = {
  GESUCHSTELLER: 'GESUCHSTELLER' as Kontoinhaberin,
  VATER: 'VATER' as Kontoinhaberin,
  MUTTER: 'MUTTER' as Kontoinhaberin,
  SOZIALDIENST_INSTITUTION: 'SOZIALDIENST_INSTITUTION' as Kontoinhaberin,
  ANDERE: 'ANDERE' as Kontoinhaberin,
};
