/**
 * STIP Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Land =
  | 'CH'
  | 'AF'
  | 'EG'
  | 'AL'
  | 'DZ'
  | 'AD'
  | 'AO'
  | 'AG'
  | 'GQ'
  | 'AR'
  | 'AM'
  | 'AZ'
  | 'ET'
  | 'AU'
  | 'BS'
  | 'BH'
  | 'BD'
  | 'BB'
  | 'BY'
  | 'BE'
  | 'BZ'
  | 'BJ'
  | 'BT'
  | 'BO'
  | 'BA'
  | 'BR'
  | 'BN'
  | 'BG'
  | 'BF'
  | 'BI'
  | 'CV'
  | 'CL'
  | 'CN'
  | 'CK'
  | 'CR'
  | 'CI'
  | 'DK'
  | 'DE'
  | 'DM'
  | 'DO'
  | 'DJ'
  | 'EC'
  | 'SV'
  | 'ER'
  | 'EE'
  | 'SZ'
  | 'FJ'
  | 'FI'
  | 'FR'
  | 'GA'
  | 'GM'
  | 'GE'
  | 'GH'
  | 'GD'
  | 'GR'
  | 'GT'
  | 'GN'
  | 'GW'
  | 'GF'
  | 'HT'
  | 'VA'
  | 'HN'
  | 'IN'
  | 'ID'
  | 'IQ'
  | 'IR'
  | 'IE'
  | 'IS'
  | 'IL'
  | 'IT'
  | 'JM'
  | 'JP'
  | 'YD'
  | 'JO'
  | 'KH'
  | 'CM'
  | 'CA'
  | 'KZ'
  | 'QA'
  | 'KE'
  | 'KG'
  | 'KI'
  | 'CO'
  | 'KM'
  | 'CG'
  | 'CD'
  | 'KR'
  | 'KP'
  | 'KS'
  | 'HR'
  | 'CU'
  | 'KW'
  | 'LA'
  | 'LS'
  | 'LV'
  | 'LB'
  | 'LR'
  | 'LY'
  | 'LI'
  | 'LT'
  | 'LU'
  | 'MG'
  | 'MW'
  | 'MY'
  | 'XX'
  | 'ML'
  | 'MT'
  | 'MA'
  | 'MH'
  | 'MR'
  | 'MU'
  | 'MX'
  | 'FM'
  | 'MO'
  | 'MC'
  | 'MN'
  | 'ME'
  | 'MZ'
  | 'MM'
  | 'NA'
  | 'NR'
  | 'NP'
  | 'NZ'
  | 'NI'
  | 'NL'
  | 'NE'
  | 'NG'
  | 'NU'
  | 'MK'
  | 'NO'
  | 'OM'
  | 'AT'
  | 'PK'
  | 'PW'
  | 'PA'
  | 'PG'
  | 'PY'
  | 'PE'
  | 'PH'
  | 'PO'
  | 'PT'
  | 'RW'
  | 'RO'
  | 'RU'
  | 'SB'
  | 'ZM'
  | 'WS'
  | 'SM'
  | 'ST'
  | 'SA'
  | 'SE'
  | 'SN'
  | 'RS'
  | 'SC'
  | 'SL'
  | 'ZW'
  | 'SG'
  | 'SK'
  | 'SI'
  | 'SO'
  | 'ES'
  | 'LK'
  | 'KN'
  | 'LC'
  | 'VC'
  | 'ZA'
  | 'SD'
  | 'SS'
  | 'SR'
  | 'SY'
  | 'TJ'
  | 'TZ'
  | 'TH'
  | 'TL'
  | 'TG'
  | 'TO'
  | 'TT'
  | 'TD'
  | 'CZ'
  | 'TN'
  | 'TU'
  | 'TM'
  | 'TV'
  | 'UG'
  | 'UA'
  | 'HU'
  | 'UY'
  | 'UZ'
  | 'VU'
  | 'VE'
  | 'AE'
  | 'US'
  | 'GB'
  | 'VN'
  | 'CF'
  | 'CY';

export const Land = {
  CH: 'CH' as Land,
  AF: 'AF' as Land,
  EG: 'EG' as Land,
  AL: 'AL' as Land,
  DZ: 'DZ' as Land,
  AD: 'AD' as Land,
  AO: 'AO' as Land,
  AG: 'AG' as Land,
  GQ: 'GQ' as Land,
  AR: 'AR' as Land,
  AM: 'AM' as Land,
  AZ: 'AZ' as Land,
  ET: 'ET' as Land,
  AU: 'AU' as Land,
  BS: 'BS' as Land,
  BH: 'BH' as Land,
  BD: 'BD' as Land,
  BB: 'BB' as Land,
  BY: 'BY' as Land,
  BE: 'BE' as Land,
  BZ: 'BZ' as Land,
  BJ: 'BJ' as Land,
  BT: 'BT' as Land,
  BO: 'BO' as Land,
  BA: 'BA' as Land,
  BR: 'BR' as Land,
  BN: 'BN' as Land,
  BG: 'BG' as Land,
  BF: 'BF' as Land,
  BI: 'BI' as Land,
  CV: 'CV' as Land,
  CL: 'CL' as Land,
  CN: 'CN' as Land,
  CK: 'CK' as Land,
  CR: 'CR' as Land,
  CI: 'CI' as Land,
  DK: 'DK' as Land,
  DE: 'DE' as Land,
  DM: 'DM' as Land,
  DO: 'DO' as Land,
  DJ: 'DJ' as Land,
  EC: 'EC' as Land,
  SV: 'SV' as Land,
  ER: 'ER' as Land,
  EE: 'EE' as Land,
  SZ: 'SZ' as Land,
  FJ: 'FJ' as Land,
  FI: 'FI' as Land,
  FR: 'FR' as Land,
  GA: 'GA' as Land,
  GM: 'GM' as Land,
  GE: 'GE' as Land,
  GH: 'GH' as Land,
  GD: 'GD' as Land,
  GR: 'GR' as Land,
  GT: 'GT' as Land,
  GN: 'GN' as Land,
  GW: 'GW' as Land,
  GF: 'GF' as Land,
  HT: 'HT' as Land,
  VA: 'VA' as Land,
  HN: 'HN' as Land,
  IN: 'IN' as Land,
  ID: 'ID' as Land,
  IQ: 'IQ' as Land,
  IR: 'IR' as Land,
  IE: 'IE' as Land,
  IS: 'IS' as Land,
  IL: 'IL' as Land,
  IT: 'IT' as Land,
  JM: 'JM' as Land,
  JP: 'JP' as Land,
  YD: 'YD' as Land,
  JO: 'JO' as Land,
  KH: 'KH' as Land,
  CM: 'CM' as Land,
  CA: 'CA' as Land,
  KZ: 'KZ' as Land,
  QA: 'QA' as Land,
  KE: 'KE' as Land,
  KG: 'KG' as Land,
  KI: 'KI' as Land,
  CO: 'CO' as Land,
  KM: 'KM' as Land,
  CG: 'CG' as Land,
  CD: 'CD' as Land,
  KR: 'KR' as Land,
  KP: 'KP' as Land,
  KS: 'KS' as Land,
  HR: 'HR' as Land,
  CU: 'CU' as Land,
  KW: 'KW' as Land,
  LA: 'LA' as Land,
  LS: 'LS' as Land,
  LV: 'LV' as Land,
  LB: 'LB' as Land,
  LR: 'LR' as Land,
  LY: 'LY' as Land,
  LI: 'LI' as Land,
  LT: 'LT' as Land,
  LU: 'LU' as Land,
  MG: 'MG' as Land,
  MW: 'MW' as Land,
  MY: 'MY' as Land,
  XX: 'XX' as Land,
  ML: 'ML' as Land,
  MT: 'MT' as Land,
  MA: 'MA' as Land,
  MH: 'MH' as Land,
  MR: 'MR' as Land,
  MU: 'MU' as Land,
  MX: 'MX' as Land,
  FM: 'FM' as Land,
  MO: 'MO' as Land,
  MC: 'MC' as Land,
  MN: 'MN' as Land,
  ME: 'ME' as Land,
  MZ: 'MZ' as Land,
  MM: 'MM' as Land,
  NA: 'NA' as Land,
  NR: 'NR' as Land,
  NP: 'NP' as Land,
  NZ: 'NZ' as Land,
  NI: 'NI' as Land,
  NL: 'NL' as Land,
  NE: 'NE' as Land,
  NG: 'NG' as Land,
  NU: 'NU' as Land,
  MK: 'MK' as Land,
  NO: 'NO' as Land,
  OM: 'OM' as Land,
  AT: 'AT' as Land,
  PK: 'PK' as Land,
  PW: 'PW' as Land,
  PA: 'PA' as Land,
  PG: 'PG' as Land,
  PY: 'PY' as Land,
  PE: 'PE' as Land,
  PH: 'PH' as Land,
  PO: 'PO' as Land,
  PT: 'PT' as Land,
  RW: 'RW' as Land,
  RO: 'RO' as Land,
  RU: 'RU' as Land,
  SB: 'SB' as Land,
  ZM: 'ZM' as Land,
  WS: 'WS' as Land,
  SM: 'SM' as Land,
  ST: 'ST' as Land,
  SA: 'SA' as Land,
  SE: 'SE' as Land,
  SN: 'SN' as Land,
  RS: 'RS' as Land,
  SC: 'SC' as Land,
  SL: 'SL' as Land,
  ZW: 'ZW' as Land,
  SG: 'SG' as Land,
  SK: 'SK' as Land,
  SI: 'SI' as Land,
  SO: 'SO' as Land,
  ES: 'ES' as Land,
  LK: 'LK' as Land,
  KN: 'KN' as Land,
  LC: 'LC' as Land,
  VC: 'VC' as Land,
  ZA: 'ZA' as Land,
  SD: 'SD' as Land,
  SS: 'SS' as Land,
  SR: 'SR' as Land,
  SY: 'SY' as Land,
  TJ: 'TJ' as Land,
  TZ: 'TZ' as Land,
  TH: 'TH' as Land,
  TL: 'TL' as Land,
  TG: 'TG' as Land,
  TO: 'TO' as Land,
  TT: 'TT' as Land,
  TD: 'TD' as Land,
  CZ: 'CZ' as Land,
  TN: 'TN' as Land,
  TU: 'TU' as Land,
  TM: 'TM' as Land,
  TV: 'TV' as Land,
  UG: 'UG' as Land,
  UA: 'UA' as Land,
  HU: 'HU' as Land,
  UY: 'UY' as Land,
  UZ: 'UZ' as Land,
  VU: 'VU' as Land,
  VE: 'VE' as Land,
  AE: 'AE' as Land,
  US: 'US' as Land,
  GB: 'GB' as Land,
  VN: 'VN' as Land,
  CF: 'CF' as Land,
  CY: 'CY' as Land,
};
