/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Niederlassungsstatus =
  | 'NIEDERLASSUNGSBEWILLIGUNG_L'
  | 'NIEDERLASSUNGSBEWILLIGUNG_B'
  | 'NIEDERLASSUNGSBEWILLIGUNG_C'
  | 'NIEDERLASSUNGSBEWILLIGUNG_G';

export const Niederlassungsstatus = {
  NIEDERLASSUNGSBEWILLIGUNG_L:
    'NIEDERLASSUNGSBEWILLIGUNG_L' as Niederlassungsstatus,
  NIEDERLASSUNGSBEWILLIGUNG_B:
    'NIEDERLASSUNGSBEWILLIGUNG_B' as Niederlassungsstatus,
  NIEDERLASSUNGSBEWILLIGUNG_C:
    'NIEDERLASSUNGSBEWILLIGUNG_C' as Niederlassungsstatus,
  NIEDERLASSUNGSBEWILLIGUNG_G:
    'NIEDERLASSUNGSBEWILLIGUNG_G' as Niederlassungsstatus,
};
