/**
 * STIP Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Niederlassungsstatus } from './niederlassungsstatus';
import { AdresseDTO } from './adresseDTO';
import { Zivilstand } from './zivilstand';
import { Anrede } from './anrede';
import { Land } from './land';
import { Wohnsitz } from './wohnsitz';

export interface PersonInAusbildungDTO {
  id: string;
  adresse: AdresseDTO;
  sozialversicherungsnummer: string;
  name: string;
  vorname: string;
  anrede: Anrede;
  identischerZivilrechtlicherWohnsitz: boolean;
  izvOrt?: string;
  izvPLZ?: string;
  email: string;
  telefonnummer: string;
  geburtsdatum: Date;
  nationalitaet: Land;
  heimatort?: string;
  niederlassungsstatus?: Niederlassungsstatus;
  zivilstand?: Zivilstand;
  wohnsitz: Wohnsitz;
  sozialhilfebeitraege: boolean;
  quellenbesteuert: boolean;
  kinder: boolean;
  digitaleKommunikation: boolean;
}
