/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Wohnsitz = 'EIGENER_HAUSHALT' | 'FAMILIE' | 'MUTTER_VATER';

export const Wohnsitz = {
    EIGENER_HAUSHALT: 'EIGENER_HAUSHALT' as Wohnsitz,
    FAMILIE: 'FAMILIE' as Wohnsitz,
    MUTTER_VATER: 'MUTTER_VATER' as Wohnsitz
};

