/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 */
export type WohnsitzKanton = 'AG' | 'AI' | 'AR' | 'BL' | 'BS' | 'BE' | 'FR' | 'GE' | 'GL' | 'GR' | 'JU' | 'LU' | 'NE' | 'NW' | 'OW' | 'SG' | 'SH' | 'SZ' | 'SO' | 'TI' | 'TG' | 'UR' | 'VD' | 'VS' | 'ZG' | 'ZH' | 'AUSLAND';

export const WohnsitzKanton = {
    AG: 'AG' as WohnsitzKanton,
    AI: 'AI' as WohnsitzKanton,
    AR: 'AR' as WohnsitzKanton,
    BL: 'BL' as WohnsitzKanton,
    BS: 'BS' as WohnsitzKanton,
    BE: 'BE' as WohnsitzKanton,
    FR: 'FR' as WohnsitzKanton,
    GE: 'GE' as WohnsitzKanton,
    GL: 'GL' as WohnsitzKanton,
    GR: 'GR' as WohnsitzKanton,
    JU: 'JU' as WohnsitzKanton,
    LU: 'LU' as WohnsitzKanton,
    NE: 'NE' as WohnsitzKanton,
    NW: 'NW' as WohnsitzKanton,
    OW: 'OW' as WohnsitzKanton,
    SG: 'SG' as WohnsitzKanton,
    SH: 'SH' as WohnsitzKanton,
    SZ: 'SZ' as WohnsitzKanton,
    SO: 'SO' as WohnsitzKanton,
    TI: 'TI' as WohnsitzKanton,
    TG: 'TG' as WohnsitzKanton,
    UR: 'UR' as WohnsitzKanton,
    VD: 'VD' as WohnsitzKanton,
    VS: 'VS' as WohnsitzKanton,
    ZG: 'ZG' as WohnsitzKanton,
    ZH: 'ZH' as WohnsitzKanton,
    AUSLAND: 'AUSLAND' as WohnsitzKanton
};

