/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Zivilstand = 'LEDIG' | 'VERHEIRATET' | 'KONKUBINAT' | 'EINGETRAGENE_PARTNERSCHAFT' | 'GESCHIEDEN_GERICHTLICH' | 'AUFGELOESTE_PARTNERSCHAFT' | 'VERWITWET';

export const Zivilstand = {
    LEDIG: 'LEDIG' as Zivilstand,
    VERHEIRATET: 'VERHEIRATET' as Zivilstand,
    KONKUBINAT: 'KONKUBINAT' as Zivilstand,
    EINGETRAGENE_PARTNERSCHAFT: 'EINGETRAGENE_PARTNERSCHAFT' as Zivilstand,
    GESCHIEDEN_GERICHTLICH: 'GESCHIEDEN_GERICHTLICH' as Zivilstand,
    AUFGELOESTE_PARTNERSCHAFT: 'AUFGELOESTE_PARTNERSCHAFT' as Zivilstand,
    VERWITWET: 'VERWITWET' as Zivilstand
};

