/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungsort } from './ausbildungsort';
import { Bildungsart } from './bildungsart';
import { AusbildungsstaetteUpdate } from './ausbildungsstaetteUpdate';

/**
 * 
 */
export interface AusbildungsgangUpdate { 
    /**
     * 
     */
    bezeichnungDe: string;
    /**
     * 
     */
    bezeichnungFr: string;
    ausbildungsrichtung: Bildungsart;
    ausbildungsstaette: AusbildungsstaetteUpdate;
    ausbildungsort: Ausbildungsort;
}



