/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 */
export type Bildungsart = 'GYMNASIALE_MATURITAETSSCHULEN' | 'SCHULEN_FUER_ALLGEMEINBILDUNG' | 'VOLLZEITBERUFSSCHULEN' | 'LEHREN_ANLEHREN' | 'BERUFSMATURITAET_NACH_LEHRE' | 'HOEHERE_BERUFSBILDUNG' | 'FACHHOCHSCHULEN' | 'UNIVERSITAETEN_ETH';

export const Bildungsart = {
    GYMNASIALE_MATURITAETSSCHULEN: 'GYMNASIALE_MATURITAETSSCHULEN' as Bildungsart,
    SCHULEN_FUER_ALLGEMEINBILDUNG: 'SCHULEN_FUER_ALLGEMEINBILDUNG' as Bildungsart,
    VOLLZEITBERUFSSCHULEN: 'VOLLZEITBERUFSSCHULEN' as Bildungsart,
    LEHREN_ANLEHREN: 'LEHREN_ANLEHREN' as Bildungsart,
    BERUFSMATURITAET_NACH_LEHRE: 'BERUFSMATURITAET_NACH_LEHRE' as Bildungsart,
    HOEHERE_BERUFSBILDUNG: 'HOEHERE_BERUFSBILDUNG' as Bildungsart,
    FACHHOCHSCHULEN: 'FACHHOCHSCHULEN' as Bildungsart,
    UNIVERSITAETEN_ETH: 'UNIVERSITAETEN_ETH' as Bildungsart
};

