/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type ElternUnbekanntheitsGrund = 'UNBEKANNTER_AUFENTHALTSORT' | 'FEHLENDE_ANERKENNUNG';

export const ElternUnbekanntheitsGrund = {
    UNBEKANNTER_AUFENTHALTSORT: 'UNBEKANNTER_AUFENTHALTSORT' as ElternUnbekanntheitsGrund,
    FEHLENDE_ANERKENNUNG: 'FEHLENDE_ANERKENNUNG' as ElternUnbekanntheitsGrund
};

