/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ausbildungssituation } from './ausbildungssituation';
import { Wohnsitz } from './wohnsitz';

/**
 * 
 */
export interface GeschwisterUpdate { 
    vorname: string;
    /**
     * dd.MM.YYYY
     */
    geburtsdatum: string;
    wohnsitz: Wohnsitz;
    ausbildungssituation: Ausbildungssituation;
    id?: string;
    /**
     * Required wenn Wohnsitz.MUTTER_VATER.
     */
    wohnsitzAnteilMutter?: number;
    /**
     * Required wenn Wohnsitz.MUTTER_VATER.
     */
    wohnsitzAnteilVater?: number;
    nachname: string;
}



