/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Gesuchstatus = 'OFFEN' | 'IN_BEARBEITUNG' | 'EINGEREICHT' | 'NICHT_KOMPLETT_EINGEREICHT' | 'NICHT_KOMPLETT_EINGEREICHT_NACHFRIST';

export const Gesuchstatus = {
    OFFEN: 'OFFEN' as Gesuchstatus,
    IN_BEARBEITUNG: 'IN_BEARBEITUNG' as Gesuchstatus,
    EINGEREICHT: 'EINGEREICHT' as Gesuchstatus,
    NICHT_KOMPLETT_EINGEREICHT: 'NICHT_KOMPLETT_EINGEREICHT' as Gesuchstatus,
    NICHT_KOMPLETT_EINGEREICHT_NACHFRIST: 'NICHT_KOMPLETT_EINGEREICHT_NACHFRIST' as Gesuchstatus
};

