/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 */
export type Kontoinhaber = 'GESUCHSTELLER' | 'VATER' | 'MUTTER' | 'SOZIALDIENST_INSTITUTION' | 'ANDERE';

export const Kontoinhaber = {
    GESUCHSTELLER: 'GESUCHSTELLER' as Kontoinhaber,
    VATER: 'VATER' as Kontoinhaber,
    MUTTER: 'MUTTER' as Kontoinhaber,
    SOZIALDIENST_INSTITUTION: 'SOZIALDIENST_INSTITUTION' as Kontoinhaber,
    ANDERE: 'ANDERE' as Kontoinhaber
};

