/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WohnsitzKanton } from './wohnsitzKanton';
import { Bildungsart } from './bildungsart';
import { Taetigskeitsart } from './taetigskeitsart';

/**
 * 
 */
export interface LebenslaufItemUpdate { 
    wohnsitz: WohnsitzKanton;
    id?: string;
    beschreibung: string;
    bildungsart?: Bildungsart;
    taetigskeitsart?: Taetigskeitsart;
    /**
     * Datum im Format mm.YYYY
     */
    von: string;
    /**
     * Datum im Format mm.YYYY
     */
    bis: string;
}



