/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type Niederlassungsstatus = 'NIEDERLASSUNGSBEWILLIGUNG_C' | 'AUFENTHALTSBEWILLIGUNG_B' | 'FLUECHTLING';

export const Niederlassungsstatus = {
    NIEDERLASSUNGSBEWILLIGUNG_C: 'NIEDERLASSUNGSBEWILLIGUNG_C' as Niederlassungsstatus,
    AUFENTHALTSBEWILLIGUNG_B: 'AUFENTHALTSBEWILLIGUNG_B' as Niederlassungsstatus,
    FLUECHTLING: 'FLUECHTLING' as Niederlassungsstatus
};

