/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';

export interface Partner { 
    adresse: Adresse;
    vorname: string;
    geburtsdatum: string;
    /**
     * 
     */
    sozialversicherungsnummer: string;
    nachname: string;
    ausbildungMitEinkommenOderErwerbstaetig?: boolean;
    /**
     * Required falls ausbildungMitEinkommenOderErwerbstaetig true ist
     */
    jahreseinkommen?: number;
    /**
     * Required falls ausbildungMitEinkommenOderErwerbstaetig true ist
     */
    fahrkosten?: number;
    /**
     * Required falls ausbildungMitEinkommenOderErwerbstaetig true ist
     */
    verpflegungskosten?: number;
}

