/**
 * STIP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Niederlassungsstatus } from './niederlassungsstatus';
import { Sprache } from './sprache';
import { Zivilstand } from './zivilstand';
import { Anrede } from './anrede';
import { Land } from './land';
import { Wohnsitz } from './wohnsitz';

export interface PersonInAusbildung { 
    adresse: Adresse;
    sozialversicherungsnummer: string;
    vorname: string;
    anrede: Anrede;
    identischerZivilrechtlicherWohnsitz: boolean;
    email: string;
    telefonnummer: string;
    geburtsdatum: string;
    nationalitaet: Land;
    /**
     * Required nur wenn Land = CH
     */
    heimatort?: string;
    niederlassungsstatus?: Niederlassungsstatus;
    zivilstand?: Zivilstand;
    wohnsitz: Wohnsitz;
    /**
     * Required wenn Wohnsitz.MUTTER_VATER.
     */
    wohnsitzAnteilMutter?: number;
    /**
     * Required wenn Wohnsitz.MUTTER_VATER.
     */
    wohnsitzAnteilVater?: number;
    sozialhilfebeitraege: boolean;
    quellenbesteuert: boolean;
    digitaleKommunikation: boolean;
    /**
     * Required nur wenn Land = CH
     */
    vormundschaft?: boolean;
    nachname: string;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzOrt?: string;
    /**
     * Required wenn identischerZivilrechtlicherWohnsitz = false
     */
    identischerZivilrechtlicherWohnsitzPLZ?: string;
    korrespondenzSprache: Sprache;
}



